spring:
  application:
    name: waiter-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kdswaiter.servicebus.windows.net:9093}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: ${JAAS_CONFIG}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: waiter-group-v2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.waiter_service.dto.OrderReadyEvent
        spring.json.use.type.headers: false
    topic:
      order-ready: order-ready

server:
  port: 8086

webhook:
  url: ${WEBHOOK_URL:https://webhook.site/7b320857-4148-4363-8994-554477874747}

logging:
  level:
    org.springframework.kafka: DEBUG
    com.example.waiter_service: DEBUG
