spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://fullstack-mysql-server.mysql.database.azure.com:3306/orderdb?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true&serverTimezone=UTC
    username: nidula
    password: springboot@inteli020
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 8083

# Cart Service Integration
cart-service:
  base-url: http://localhost:8080/api/cart

logging:
  level:
    com.example.order_service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

