name: Sync Auth Service to Hugging Face
on:
  push:
    branches: [dev_ishanka]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to preserve history for subtree push

      - name: Push Auth Service folder to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git subtree push --prefix services/auth-service https://ishanka1102:$HF_TOKEN@huggingface.co/spaces/ishanka1102/auth_service main
